### ISSUE TITLE
Question about planned support

### ISSUE THREAD

**Issue by UNIcodeX** [canonical/desktop_notifications.dart#24]
I arrived at this repo by way of the flutter_local_notifications linux support thread.

This project looks very promising, especially given that Canonical is behind it. My question has to do with the listed supported platforms on pub.dev. Is it planned to also support Windows notifications? It would be awesome to have something which works across the board with all supported platforms.

Currently it is listed as being supported on the pub.dev page, but I'm guessing that since there are currently no platform folders in the project, that's the reason non-Linux platforms are listed. 

So I guess my actual question is... Is Windows notification support planned or is this plugin ultimately intended to be for Linux desktop only? I've been looking into other options for Windows support, like win32.

Thanks for the work you're doing in this space. 😁

**Comment by robert-ancell** [comment]
The purpose of this package is just to implement the freedesktop.org notification specification, which means it really only works on Linux systems (as well as BSD etc). The intention is that a higher level package such as flutter_location_notifications could depend on this for the Linux specific notification functionality.

Due to a [limitation in Dart](https://github.com/dart-lang/pub/issues/2353) we can't control which platforms show on pub.dev. I mean, it *technically* could work on Windows if you had a D-Bus server running and a notifications server, but that doesn't seem likely. We've had similar confusion with other Linux Dart packages (e.g. [bluez](https://github.com/canonical/bluez.dart/issues/36)), so I'll add some information to the README to clarify this.

**Comment by robert-ancell** [comment]
[Updated README](https://github.com/canonical/desktop_notifications.dart/pull/25).
